<?php  namespace ftgr;

define('FTGR_BITE_POWER_BLAZER', 5);
define('FTGR_BITE_POWER_DRAGIRI_MIN', 30);
define('FTGR_BITE_POWER_DRAGIRI_MAX', 40);
define('FTGR_BITE_POWER_FENIIXIS', 3);
define('FTGR_BITE_POWER_FIREE_BEE', 10);
define('FTGR_BITE_POWER_FLIKE', 2);
define('FTGR_BITE_POWER_HARTVILE', 3);
define('FTGR_BITE_POWER_REE_BEE', 5);
define('FTGR_BITE_POWER_REEMON', 15);
define('FTGR_BITE_POWER_SKELESTORM', 10);
define('FTGR_BITE_ACCURACY', 95);
