<?php  namespace iMagine;

require_once realpath(__DIR__ . '/airram.php');
require_once realpath(__DIR__ . '/antennabeams.php');
require_once realpath(__DIR__ . '/bite.php');
require_once realpath(__DIR__ . '/bladeburst.php');
require_once realpath(__DIR__ . '/burn.php');
require_once realpath(__DIR__ . '/daze.php');
require_once realpath(__DIR__ . '/deroot.php');
require_once realpath(__DIR__ . '/echolocate.php');
require_once realpath(__DIR__ . '/electroshade.php');
require_once realpath(__DIR__ . '/fireflare.php');
require_once realpath(__DIR__ . '/flyby.php');
require_once realpath(__DIR__ . '/hornit.php');
require_once realpath(__DIR__ . '/kick.php');
require_once realpath(__DIR__ . '/lightningstrike.php');
require_once realpath(__DIR__ . '/lovesfall.php');
require_once realpath(__DIR__ . '/metalpetal.php');
require_once realpath(__DIR__ . '/needlethorn.php');
require_once realpath(__DIR__ . '/projectiles.php');
require_once realpath(__DIR__ . '/repstrike.php');
require_once realpath(__DIR__ . '/scratch.php');
require_once realpath(__DIR__ . '/staticshock.php');
require_once realpath(__DIR__ . '/sting.php');
require_once realpath(__DIR__ . '/stomp.php');
require_once realpath(__DIR__ . '/tailwhip.php');
require_once realpath(__DIR__ . '/trample.php');
require_once realpath(__DIR__ . '/windwhap.php');
