<?php

define('FTGR_SCRATCH_NAME', itemOf(array('EN' => 'Scratch'), FTGR_LANG));
define('FTGR_SCRATCH_POWER_FLIKE', 3);
define('FTGR_SCRATCH_POWER_NIGHTWING', 4);
define('FTGR_SCRATCH_POWER_REE_BEE', 8);
define('FTGR_SCRATCH_POWER_BLAZER', 8);
define('FTGR_SCRATCH_POWER_HARTVILE', 10);
define('FTGR_SCRATCH_POWER_FIREE_BEE', 12);
define('FTGR_SCRATCH_POWER_FENIIXIS', 20);
define('FTGR_SCRATCH_ACCURACY', 70);
