<?php  namespace iMagine;

define('IMAGINE_SCRATCH_POWER_FLIKE', 3);
define('IMAGINE_SCRATCH_POWER_NIGHTWING', 4);
define('IMAGINE_SCRATCH_POWER_REE_BEE', 8);
define('IMAGINE_SCRATCH_POWER_BLAZER', 8);
define('IMAGINE_SCRATCH_POWER_HARTVILE', 10);
define('IMAGINE_SCRATCH_POWER_FIREE_BEE', 12);
define('IMAGINE_SCRATCH_POWER_FENIIXIS', 20);
define('IMAGINE_SCRATCH_ACCURACY', 70);
